# == Schema Information
#
# Table name: legal_informations
#
#  id                :integer          not null, primary key
#  name              :string
#  short_description :text
#  content           :text
#  publication_date  :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LegalInformationsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LegalInformation. As you add validations to LegalInformation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LegalInformationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all legal_informations as @legal_informations" do
      legal_information = LegalInformation.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:legal_informations)).to eq([legal_information])
    end
  end

  describe "GET #show" do
    it "assigns the requested legal_information as @legal_information" do
      legal_information = LegalInformation.create! valid_attributes
      get :show, {:id => legal_information.to_param}, valid_session
      expect(assigns(:legal_information)).to eq(legal_information)
    end
  end

  describe "GET #new" do
    it "assigns a new legal_information as @legal_information" do
      get :new, {}, valid_session
      expect(assigns(:legal_information)).to be_a_new(LegalInformation)
    end
  end

  describe "GET #edit" do
    it "assigns the requested legal_information as @legal_information" do
      legal_information = LegalInformation.create! valid_attributes
      get :edit, {:id => legal_information.to_param}, valid_session
      expect(assigns(:legal_information)).to eq(legal_information)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LegalInformation" do
        expect {
          post :create, {:legal_information => valid_attributes}, valid_session
        }.to change(LegalInformation, :count).by(1)
      end

      it "assigns a newly created legal_information as @legal_information" do
        post :create, {:legal_information => valid_attributes}, valid_session
        expect(assigns(:legal_information)).to be_a(LegalInformation)
        expect(assigns(:legal_information)).to be_persisted
      end

      it "redirects to the created legal_information" do
        post :create, {:legal_information => valid_attributes}, valid_session
        expect(response).to redirect_to(LegalInformation.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved legal_information as @legal_information" do
        post :create, {:legal_information => invalid_attributes}, valid_session
        expect(assigns(:legal_information)).to be_a_new(LegalInformation)
      end

      it "re-renders the 'new' template" do
        post :create, {:legal_information => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested legal_information" do
        legal_information = LegalInformation.create! valid_attributes
        put :update, {:id => legal_information.to_param, :legal_information => new_attributes}, valid_session
        legal_information.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested legal_information as @legal_information" do
        legal_information = LegalInformation.create! valid_attributes
        put :update, {:id => legal_information.to_param, :legal_information => valid_attributes}, valid_session
        expect(assigns(:legal_information)).to eq(legal_information)
      end

      it "redirects to the legal_information" do
        legal_information = LegalInformation.create! valid_attributes
        put :update, {:id => legal_information.to_param, :legal_information => valid_attributes}, valid_session
        expect(response).to redirect_to(legal_information)
      end
    end

    context "with invalid params" do
      it "assigns the legal_information as @legal_information" do
        legal_information = LegalInformation.create! valid_attributes
        put :update, {:id => legal_information.to_param, :legal_information => invalid_attributes}, valid_session
        expect(assigns(:legal_information)).to eq(legal_information)
      end

      it "re-renders the 'edit' template" do
        legal_information = LegalInformation.create! valid_attributes
        put :update, {:id => legal_information.to_param, :legal_information => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested legal_information" do
      legal_information = LegalInformation.create! valid_attributes
      expect {
        delete :destroy, {:id => legal_information.to_param}, valid_session
      }.to change(LegalInformation, :count).by(-1)
    end

    it "redirects to the legal_informations list" do
      legal_information = LegalInformation.create! valid_attributes
      delete :destroy, {:id => legal_information.to_param}, valid_session
      expect(response).to redirect_to(legal_informations_url)
    end
  end

end
