# == Schema Information
#
# Table name: packagings
#
#  id             :integer          not null, primary key
#  package_id     :integer
#  user_id        :integer
#  refund_percent :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PackagingsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Packaging. As you add validations to Packaging, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PackagingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all packagings as @packagings" do
      packaging = Packaging.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:packagings)).to eq([packaging])
    end
  end

  describe "GET #show" do
    it "assigns the requested packaging as @packaging" do
      packaging = Packaging.create! valid_attributes
      get :show, {:id => packaging.to_param}, valid_session
      expect(assigns(:packaging)).to eq(packaging)
    end
  end

  describe "GET #new" do
    it "assigns a new packaging as @packaging" do
      get :new, {}, valid_session
      expect(assigns(:packaging)).to be_a_new(Packaging)
    end
  end

  describe "GET #edit" do
    it "assigns the requested packaging as @packaging" do
      packaging = Packaging.create! valid_attributes
      get :edit, {:id => packaging.to_param}, valid_session
      expect(assigns(:packaging)).to eq(packaging)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Packaging" do
        expect {
          post :create, {:packaging => valid_attributes}, valid_session
        }.to change(Packaging, :count).by(1)
      end

      it "assigns a newly created packaging as @packaging" do
        post :create, {:packaging => valid_attributes}, valid_session
        expect(assigns(:packaging)).to be_a(Packaging)
        expect(assigns(:packaging)).to be_persisted
      end

      it "redirects to the created packaging" do
        post :create, {:packaging => valid_attributes}, valid_session
        expect(response).to redirect_to(Packaging.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved packaging as @packaging" do
        post :create, {:packaging => invalid_attributes}, valid_session
        expect(assigns(:packaging)).to be_a_new(Packaging)
      end

      it "re-renders the 'new' template" do
        post :create, {:packaging => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested packaging" do
        packaging = Packaging.create! valid_attributes
        put :update, {:id => packaging.to_param, :packaging => new_attributes}, valid_session
        packaging.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested packaging as @packaging" do
        packaging = Packaging.create! valid_attributes
        put :update, {:id => packaging.to_param, :packaging => valid_attributes}, valid_session
        expect(assigns(:packaging)).to eq(packaging)
      end

      it "redirects to the packaging" do
        packaging = Packaging.create! valid_attributes
        put :update, {:id => packaging.to_param, :packaging => valid_attributes}, valid_session
        expect(response).to redirect_to(packaging)
      end
    end

    context "with invalid params" do
      it "assigns the packaging as @packaging" do
        packaging = Packaging.create! valid_attributes
        put :update, {:id => packaging.to_param, :packaging => invalid_attributes}, valid_session
        expect(assigns(:packaging)).to eq(packaging)
      end

      it "re-renders the 'edit' template" do
        packaging = Packaging.create! valid_attributes
        put :update, {:id => packaging.to_param, :packaging => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested packaging" do
      packaging = Packaging.create! valid_attributes
      expect {
        delete :destroy, {:id => packaging.to_param}, valid_session
      }.to change(Packaging, :count).by(-1)
    end

    it "redirects to the packagings list" do
      packaging = Packaging.create! valid_attributes
      delete :destroy, {:id => packaging.to_param}, valid_session
      expect(response).to redirect_to(packagings_url)
    end
  end

end
